<?php

$modversion['name'] = _DROPDOWN_NAME;
$modversion['version'] = 0.20;
$modversion['description'] = _DROPDOWN_DESC;
$modversion['author'] = 'frankblack<br>( frankblack@01019freenet.de )';
$modversion['credits'] = 'The XOOPS Project';
$modversion['help'] = 'dropdown.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'dropdown.gif';
$modversion['dirname'] = 'dropdown';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'dropdown';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
$modversion['blocks'][1]['file'] = 'dropdownmenu.php';
$modversion['blocks'][1]['name'] = _DROPDOWN_BNAME;
$modversion['blocks'][1]['description'] = 'Zeigt individuelles Dropdown-Menu an';
$modversion['blocks'][1]['show_func'] = 'block_DROPDOWN_show';

// Menu
$modversion['hasMain'] = 0;
